IT_Fundamentals_MCQs =[
     {"question": "What does CPU stand for?", 
        "options": ["A. Central Processing Unit", "B. Central Print Unit", "C. Central Process Unit", "D. Control Processing Unit"], 
        "answer":["A. Central Processing Unit"],"multiple": False},
    {"question": "Which device is used to connect computers in a network?", 
        "options": ["A. Router", "B. Monitor", "C. Keyboard", "D. Printer"], 
        "answer": ["A. Router"],"multiple": False},
    {"question": "What is the primary function of RAM?",
        "options": ["A. Storing permanent data", "B. Storing temporary data", "C. Storing instructions for CPU", "D. All of the above"],
        "answer": ["B. Storing temporary data"],"multiple": False},
    {"question": "What does 'HTTP' stand for?", 
        "options": ["A. Hyper Text Transfer Protocol", "B. Hyper Text Transmission Protocol", "C. High Text Transfer Protocol", "D. High Text Transmission Protocol"], 
        "answer": ["A. Hyper Text Transfer Protocol"],"multiple": False},
    {"question": "Which of these is an operating system?", 
        "options": ["A. Windows", "B. Microsoft Office", "C. Photoshop", "D. Google Chrome"], 
        "answer": ["A. Windows"],"multiple": False},
    {"question": "What does RAM stand for?", 
        "options": ["A. Random Access Memory", "B. Read Access Memory", "C. Ready Access Memory", "D. Real Access Memory"], 
        "answer": ["A. Random Access Memory"],"multiple": False},
    {"question": "Which programming language is primarily used for web development?", 
        "options": ["A. Python", "B. Java", "C. HTML", "D. C++"], 
        "answer": ["C. HTML"],"multiple": False},
    {"question": "Which company developed the Windows operating system?", 
        "options": ["A. Apple", "B. Microsoft", "C. IBM", "D. Google"], 
        "answer": ["B. Microsoft"],"multiple": False},
    {"question": "What does URL stand for?", 
        "options": ["A. Uniform Resource Locator", "B. Uniform Resource Link", "C. Uniform Retrieval Locator", "D. Unified Resource Locator"], 
        "answer": ["A. Uniform Resource Locator"],"multiple": False},
    {"question": "Which of the following is a type of malware?", 
        "options": ["A. Firewall", "B. Antivirus", "C. Trojan Horse", "D. Router"], 
        "answer": ["C. Trojan Horse"],"multiple": False},
    {"question": "What is the main function of the ALU in a computer?", 
        "options": ["A. Perform arithmetic and logic operations", "B. Manage memory", "C. Control data flow", "D. Connect to the internet"], 
        "answer": ["A. Perform arithmetic and logic operations"],"multiple": False},
    {"question": "What does SSD stand for?", 
        "options": ["A. Solid State Drive", "B. Solid Speed Drive", "C. Standard State Drive", "D. Super State Drive"], 
        "answer": ["A. Solid State Drive"],"multiple": False},
    {"question": "Which language is used for styling web pages?", 
        "options": ["A. HTML", "B. CSS", "C. JavaScript", "D. SQL"], 
        "answer": ["B. CSS"],"multiple": False},
    {"question": "What is the main purpose of a database?", 
        "options": ["A. Store data", "B. Display data", "C. Transfer data", "D. Encrypt data"], 
        "answer": ["A. Store data"],"multiple": False},
    {"question": "What is a firewall used for?", 
        "options": ["A. Protecting against malware", "B. Managing network traffic", "C. Storing data", "D. Increasing internet speed"], 
        "answer": ["B. Managing network traffic"],"multiple": False},
    {"question": "Which protocol is used to send emails?", 
        "options": ["A. FTP", "B. SMTP", "C. HTTP", "D. SNMP"], 
        "answer": ["B. SMTP"],"multiple": False},
    {"question": "What does GUI stand for?", 
        "options": ["A. Graphical User Interface", "B. General User Interface", "C. Generic User Interface", "D. Graphical Unified Interface"], 
        "answer": ["A. Graphical User Interface"],"multiple": False},
    {"question": "Which device is used to input data into a computer?", 
        "options": ["A. Monitor", "B. Printer", "C. Keyboard", "D. Speaker"], 
        "answer": ["C. Keyboard"],"multiple": False},
    {"question": "What does IP stand for in IP address?", 
        "options": ["A. Internet Protocol", "B. Internal Protocol", "C. Internet Program", "D. Internal Program"], 
        "answer": ["A. Internet Protocol"],"multiple": False},
    {"question": "Which of these is an example of an output device?", 
        "options": ["A. Scanner", "B. Mouse", "C. Printer", "D. Microphone"], 
        "answer": ["C. Printer"],"multiple": False},
    {"question": "What is an IP address used for?", 
        "options": ["A. Identifying a computer on a network", "B. Encrypting data", "C. Running applications", "D. Storing files"], 
        "answer": ["A. Identifying a computer on a network"],"multiple": False},
    {"question": "What is the function of a router?", 
        "options": ["A. Store data", "B. Direct data traffic", "C. Encrypt data", "D. Run applications"], 
        "answer": ["B. Direct data traffic"],"multiple": False},
    {"question": "Which of these is a popular programming language for data analysis?", 
        "options": ["A. JavaScript", "B. C++", "C. R", "D. PHP"], 
        "answer": ["C. R"],"multiple": False},
    {"question": "What does VPN stand for?", 
        "options": ["A. Virtual Private Network", "B. Virtual Personal Network", "C. Variable Private Network", "D. Variable Personal Network"], 
        "answer": ["A. Virtual Private Network"],"multiple": False},
    {"question": "What type of software is an operating system?", 
        "options": ["A. Application software", "B. System software", "C. Utility software", "D. Development software"], 
        "answer": ["B. System software"],"multiple": False},
    {"question": "Select the components of a computer?",
        "options": ["A. CPU", "B. Mouse", "C. Monitor", "D. All of the above"],
        "answer": ["A", "B", "C"],
        "multiple": True}
] 